"""add caja_id and numero_en_caja to pedidos

Revision ID: 7f23278c91ea
Revises: 32821ad69165
Create Date: 2026-02-20 14:38:11.649215

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7f23278c91ea'
down_revision = '32821ad69165'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cash_registers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cash_registers_status'), ['status'], unique=False)
        batch_op.create_foreign_key(None, 'users', ['opened_by_id'], ['id'])
        batch_op.create_foreign_key(None, 'users', ['closed_by_id'], ['id'])

    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.alter_column('cash_register_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.create_index(batch_op.f('ix_orders_cash_register_id'), ['cash_register_id'], unique=False)

    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.drop_column('change_amount')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('change_amount', sa.NUMERIC(precision=12, scale=2), server_default=sa.text('0'), autoincrement=False, nullable=False))

    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_orders_cash_register_id'))
        batch_op.alter_column('cash_register_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('cash_registers', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_cash_registers_status'))

    # ### end Alembic commands ###
